[package]
name = "nimbus"
version = "1.0.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
thiserror = "2.0"
winit = "0.30"
tracing = "0.1"
tracing-subscriber = "0.3"
wgpu = "26.0"
cgmath = "0.18"
gltf = "1.4"
pollster = "0.4"
bytemuck = "1.23"
